language: python

addons:
    apt:
        packages:
            # http://superuser.com/a/1057144/34733
            - oracle-java8-installer
            - xmlstarlet

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"

env:
    - REQUIRES=minimum
    - REQUIRES=normal

install:
    - if [ "$TRAVIS_PYTHON_VERSION" = pypy ]; then . `tools/pypy_env.sh`; fi
    - if [ "$REQUIRES" = minimum ]; then tools/minimum_requires.sh; fi
    - pip install -e .
    - pip install -r tools/requirements.txt
    - tools/vnu.sh install
    - tools/jshint.sh install

cache: pip

script:
    # Basic stuff.
    - python setup.py check --strict --restructuredtext
    - tools/pylint_all.sh -j 2
    - py.test

    # Build the files to be uploaded to pythonhosted.org.
    - tools/build_extra_doc.sh

    # Validate HTML-related stuff.
    # This includes validating an actual HTML report (``showcase.html``).
    - tools/vnu.sh run extra_doc/_build/*.html
    - tools/css_validator.sh httpolice/reports/html.css
    - tools/jshint.sh run httpolice/reports/html.js

    # Although the main docs (``doc/``) are processed by Read the Docs,
    # we still want to check that they are building OK.
    # But first, make sure that the included API example works.
    - python doc/api_example.py && grep -q 1194 report.html
    - sphinx-build -W doc/ doc/_build/

    # Check that the source distribution includes everything it should,
    # and nothing it shouldn't (including all the files we just built).
    - check-manifest

deploy:
    on:
        tags: true
        # Only release from one of the environments.
        python: "3.5"
        condition: $REQUIRES = normal
    provider: pypi
    user: vfaronov
    password:
        secure: 11zimRwBBrsEeIa6Q6A4WHp/PghLkK1I1gSngegGle46a5VnFxqPMtdMpt3ApIC1RrwxxoT/iswngIz9QTFVgrshtuaWzwBhWNTCW/s9ENuYLZW5EFuyxct6d4ZYdWCHNZdHRfd5uv9jFNmf7pP8JOjuTQa4Q9c00VSMn/eNli4Ug7xrB6uTuDtkCFQQwsuS+yhTSZC8h4gGY3LVuEuI9cAwksiD+Ug4ilg7f6Y96OJ/Cn+dEAy3vaVfF8NmRNyd7qYRd+PRy+jX3HCxCeDZrNsxP6r56EtbfisPAvbSgz6ooqjA5TKRhvG9GD3BnLcU8S7+WYreC3ftyZZMIoMUSR52BhOgD6AP7B5Hl47oye+Q8fHEDTmOt780kkyMHHYpGrYZvFWUXfgWUxKyQSfFTxP8K7XKuu/S1IqU9AEIc+QVGtKD5sIp/jyzT15t9Eg9akVgfN9zOYZ35ruDkyr95Ua6Vb2eRl1JINB6wz00DZ9qSOONQeEyVsjZde2mfUxy9wkutHIxAuEyPNmAVofdpCCAk6G/P+avwhkfXE0W3GLDz4b6vlXNK82dcyAs6TYvO8pJzXcyfEHX5LBRu2lmpQ65WcthqT72D6P4510VAwv4otcN+dIGThwjH+vpCvfkcpQOr3QfLSERP7vc9aK3OneLAYAkyWW6cCjDVfMKSGc=
    distributions: "sdist bdist_wheel"
    # Also upload files to pythonhosted.org.
    skip_cleanup: true
    docs_dir: extra_doc/_build
